In [1]:
import pandas as pd
import numpy as np

train = pd.read_csv("./dataset/train.csv")
test = pd.read_csv("./dataset/test.csv")
sample_submission = pd.read_csv("./dataset/sample_submission.csv")

In [2]:
train

,ID,분류,제목,키워드
0,TRAIN_00000,문화:전시_공연,"용인문화재단, 인문학 콘서트 ‘당신이 모르는 뮤지컬 이야기Ⅳ’ 개최","용인문화재단,인문학,콘서트,뮤지컬,이야기,개최,인문학,콘서트,뮤지컬,이야기,용인문화..."
1,TRAIN_00001,지역,"용인 농촌테마파크, 7~8월 단체체험객 체험료 지원","용인,농촌,테마파크,단체,체험객,체험료,지원,15일,체험일,기준,용인시통합예약사이트..."
2,TRAIN_00002,지역,"용인시, 노후주택 에너지 성능 개선 신청 18일까지 연장","용인시,노후,주택,에너지,성능,개선,신청,연장,용인시청,용인시,노후,건축물,환경친화..."
3,TRAIN_00003,지역,"수원 용인 고양시,‘특례시’로 지정 도시경쟁력 증가 기대","수원,용인,고양시,특례시,지정,도시경쟁력,증가,경기,도내,인구,수원,고양,용인시,특..."
4,TRAIN_00004,국제,"용인시, 스페인 미국 국제명예자문관 위촉 대외홍보 지원 역할","용인시,스페인,미국,국제,명예,자문관,위촉,역할,대외,홍보,지원,용인시,권태면,주코..."
...,...,...,...,...
54604,TRAIN_54604,국제,"용인 아파트서 30대 여성, 아들 딸 함께 추락 ""극단 선택 추정""","용인,아파트,여성,아들,추락,극단,선택,추정,경찰,현장,유서,경위,조사,처인구,경기..."
54605,TRAIN_54605,사회:교육_시험,"용인시, '위탁부모 보수교육' 실시","용인시,위탁,부모,보수,교육,용인시,경기,남부,가정,위탁,지원,센터,시청,컨퍼런스,..."
54606,TRAIN_54606,지역,"용인시, '플랫폼 시티' 국토부에 사업인정 협의 신청","용인시,플랫폼,시티,국토부,신청,사업,인정,협의,경기,용인시,중앙토지수용위원회,국토..."
54607,TRAIN_54607,지역,"용인시 이동읍 주민자치위원회, 저소득 20가구에 밑반찬 지원","주민자치위원회,용인시,이동읍,주민,자치,위원회,가구,밑반찬,지원,용인시,처인구,이동..."
54608,TRAIN_54608,지역,"용인시-용인시공무원노조, 국무총리상 수상","용인시,용인시공무원노조,국무총리,수상,용인,홍화표,경기,용인시,용인시공무원노동조합,..."

In [3]:
test

,ID,제목,키워드
0,TEST_00000,[부고] 김태수씨 별세 외,"김태수,별세,김태수씨,서울,광남초등학,교장,별세,김윤정,이노코리아,대표,희정,한성대..."
1,TEST_00001,"신규 확진 나흘째 세자릿수... 방역당국, 핼러윈 풍선효과 차단 총력","신규,확진,나흘,세자릿수,방역당국,핼러윈,풍선,효과,차단,총력,감염증,신종,코로나바..."
2,TEST_00002,"[서경이 만난 사람] 전해철 장관 ""재정분권 강화 '지방자치 2.0 시대' 마중물 ...","전해철,장관,재정,분권,강화,지방자치,2.0,시대,마중물,마련,장관,전해철,행정안전..."
3,TEST_00003,"용인시, 12일 '장애인 구인 구직 만남의 날' 채용 행사","용인시,구인,장애인,구직,만남,채용,행사,노호근,용인특례시,장애인,취업,지원,대회의..."
4,TEST_00004,지자체 벽 터 경기지역 산단 활성화 모색,"지자체,경기,북동부,지역,산업단지,혁신단위,설정,전략,지역,연계,특성,제시,경기도경..."
...,...,...,...
23400,TEST_23400,코로나19 감염 경로 '조사중' 32.4% 최고치 일상감염 지속,"코로나19,감염,경로,조사,32.4%,최고,일상감염,지속,기준,확진자,기준,코로나1..."
23401,TEST_23401,“여행 외식해라” vs “모임 자제하라” 시민들 “어쩌란 건가” 혼란,"여행,외식,자제,vs,모임,시민들,혼란,인천국제공항,아시아나항공,한반도,일주,비행,..."
23402,TEST_23402,송철호 울산시장 배우자 용인 임야 쪼개기 매입 의혹,"임야,송철호,울산,시장,배우자,용인,매입,의혹,송철호,울산,시장,배우자,경기,용인,..."
23403,TEST_23403,여직원 배에 '자궁 모형' 올리고 사진 찍어 홍보용으로 쓴 한의사,"여직원,자궁,모형,사진,홍보용,한의사,한의원,간호조무사,동의,자궁,모형,사진,한의사..."
23404,TEST_23404,"용인시, 팜 앤 포레스트 조성 '급물살'","용인시,급물살,포레스트,조성,관광휴양복합단지,용인,특례,농어촌,관광,휴양,복합,단지..."

In [4]:
sample_submission

               ID  분류
0      TEST_00000  지역
1      TEST_00001  지역
2      TEST_00002  지역
3      TEST_00003  지역
4      TEST_00004  지역
...           ...  ..
23400  TEST_23400  지역
23401  TEST_23401  지역
23402  TEST_23402  지역
23403  TEST_23403  지역
23404  TEST_23404  지역

[23405 rows x 2 columns]